# Generated by Django 3.2.8 on 2022-03-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireside_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='payment',
            field=models.ManyToManyField(to='fireside_api.Payment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('premium', 'Premium'), ('basic', 'Basic')], max_length=10),
        ),
    ]
