# Generated by Django 4.0.2 on 2022-03-10 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fireside_api', '0002_alter_movie_age_limit_alter_movie_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='payment',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
