# Generated by Django 4.0.2 on 2022-03-20 08:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fireside_api', '0004_rename_type_movie_movie_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='create',
        ),
        migrations.AddField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('spirituality', 'Spirituality'), ('romance', 'Romance'), ('action', 'Action'), ('animation', 'Animation'), ('fiction', 'Fiction'), ('comedy', 'Comedy'), ('horror', 'Horror'), ('sports', 'Sports'), ('documentary', 'Documentary'), ('fantasy', 'Fantasy'), ('drama', 'Drama')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='flyers/thumbnail'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='age_limit',
            field=models.CharField(choices=[('Kids', 'Kids'), ('All', 'All')], max_length=10),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_type',
            field=models.CharField(choices=[('single', 'Single'), ('seasonal', 'Seasonal')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age_limit',
            field=models.CharField(choices=[('Kids', 'Kids'), ('All', 'All')], max_length=10),
        ),
    ]
