# Generated by Django 4.0.2 on 2022-03-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireside_api', '0005_remove_movie_create_movie_date_created_movie_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='age_limit',
            field=models.CharField(choices=[('All', 'All'), ('Kids', 'Kids')], max_length=10),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('comedy', 'Comedy'), ('fantasy', 'Fantasy'), ('horror', 'Horror'), ('sports', 'Sports'), ('drama', 'Drama'), ('action', 'Action'), ('romance', 'Romance'), ('animation', 'Animation'), ('spirituality', 'Spirituality'), ('fiction', 'Fiction'), ('documentary', 'Documentary')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age_limit',
            field=models.CharField(choices=[('All', 'All'), ('Kids', 'Kids')], max_length=10),
        ),
    ]
