# Generated by Django 4.0.2 on 2022-03-23 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireside_api', '0007_alter_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='age_limit',
            field=models.CharField(choices=[('Kids', 'Kids'), ('All', 'All')], max_length=10),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('fantasy', 'Fantasy'), ('spirituality', 'Spirituality'), ('documentary', 'Documentary'), ('sports', 'Sports'), ('action', 'Action'), ('drama', 'Drama'), ('horror', 'Horror'), ('animation', 'Animation'), ('fiction', 'Fiction'), ('romance', 'Romance'), ('comedy', 'Comedy')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age_limit',
            field=models.CharField(choices=[('Kids', 'Kids'), ('All', 'All')], max_length=10),
        ),
    ]
