# Generated by Django 4.0.2 on 2022-03-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireside_api', '0008_alter_movie_age_limit_alter_movie_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('documentary', 'Documentary'), ('horror', 'Horror'), ('fantasy', 'Fantasy'), ('action', 'Action'), ('fiction', 'Fiction'), ('comedy', 'Comedy'), ('romance', 'Romance'), ('sports', 'Sports'), ('drama', 'Drama'), ('animation', 'Animation'), ('spirituality', 'Spirituality')], max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_type',
            field=models.CharField(choices=[('seasonal', 'Seasonal'), ('single', 'Single')], max_length=10),
        ),
    ]
