# Generated by Django 4.0.2 on 2022-03-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireside_api', '0009_alter_movie_genre_alter_movie_movie_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('romance', 'Romance'), ('drama', 'Drama'), ('animation', 'Animation'), ('documentary', 'Documentary'), ('spirituality', 'Spirituality'), ('fantasy', 'Fantasy'), ('fiction', 'Fiction'), ('sports', 'Sports'), ('comedy', 'Comedy'), ('horror', 'Horror'), ('action', 'Action')], max_length=50),
        ),
    ]
