# Generated by Django 4.0.2 on 2022-03-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireside_api', '0010_alter_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('drama', 'Drama'), ('action', 'Action'), ('romance', 'Romance'), ('comedy', 'Comedy'), ('animation', 'Animation'), ('spirituality', 'Spirituality'), ('horror', 'Horror'), ('fantasy', 'Fantasy'), ('fiction', 'Fiction'), ('sports', 'Sports'), ('documentary', 'Documentary')], max_length=50),
        ),
    ]
