# Generated by Django 4.0.2 on 2022-03-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireside_api', '0013_alter_movie_age_limit_alter_movie_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('action', 'Action'), ('fantasy', 'Fantasy'), ('documentary', 'Documentary'), ('animation', 'Animation'), ('spirituality', 'Spirituality'), ('drama', 'Drama'), ('horror', 'Horror'), ('romance', 'Romance'), ('sports', 'Sports'), ('comedy', 'Comedy')], max_length=50),
        ),
    ]
