# Generated by Django 4.0.2 on 2022-03-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireside_api', '0014_alter_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='age_limit',
            field=models.CharField(choices=[('All', 'All'), ('Kids', 'Kids')], max_length=10),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('romance', 'Romance'), ('documentary', 'Documentary'), ('spirituality', 'Spirituality'), ('horror', 'Horror'), ('fantasy', 'Fantasy'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('action', 'Action'), ('sports', 'Sports'), ('animation', 'Animation')], max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_type',
            field=models.CharField(choices=[('single', 'Single'), ('seasonal', 'Seasonal')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age_limit',
            field=models.CharField(choices=[('All', 'All'), ('Kids', 'Kids')], max_length=10),
        ),
    ]
