# Generated by Django 4.0.2 on 2022-03-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireside_api', '0015_alter_movie_age_limit_alter_movie_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('spirituality', 'Spirituality'), ('drama', 'Drama'), ('sports', 'Sports'), ('horror', 'Horror'), ('action', 'Action'), ('comedy', 'Comedy'), ('romance', 'Romance'), ('documentary', 'Documentary'), ('fantasy', 'Fantasy'), ('fiction', 'Fiction'), ('animation', 'Animation')], max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_type',
            field=models.CharField(choices=[('seasonal', 'Seasonal'), ('single', 'Single')], max_length=10),
        ),
    ]
